version: 2.1

parameters:
  build_wheels:
    type: boolean
    default: false

orbs:
  github-actions: movermeyer/github-actions@0.0.2

workflows:
  build_wheels:
    when: << pipeline.parameters.build_wheels >>
    jobs:
      - build_manylinux
      - store_artifacts:
        requires:
          - build_manylinux
      - notify_github:
        requires:
          - store_artifacts

jobs:
  build_manylinux:
    steps:
      - checkout
      - run:
          name: Build wheels
          command: mkdir -p wheelhouse && echo "Hello" > wheelhouse/hello.whl && echo "Goodbye" > wheelhouse/goodbye.whl
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - wheelhouse
    docker:
      - image: circleci/python:3.9

  store_artifacts:
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/wheelhouse
          destination: wheelhouse
    docker:
      - image: circleci/python:3.9

  notify_github:
    steps:
      - github-actions/repository_dispatch:
        repo_name: "movermeyer/octokit_test"
        event_type: "wheel_build_complete"
    docker:
      - image: circleci/python:3.9
