version: 2.1

parameters:
  build_wheels:
    type: boolean
    default: false

orbs:
  github-actions: movermeyer/github-actions@0.0.5

workflows:
  build_wheels:
    when: << pipeline.parameters.build_wheels >>
    jobs:
      - build_manylinux
      - store_artifacts:
          requires:
            - build_manylinux

jobs:
  build_manylinux:
    steps:
      - checkout
      - run:
          name: Build wheels
          command: mkdir -p wheelhouse && echo "Hello" > wheelhouse/hello.whl && echo "Goodbye" > wheelhouse/goodbye.whl
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - wheelhouse
    docker:
      - image: circleci/python:3.9

  store_artifacts:
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/wheelhouse
          destination: wheelhouse
      - github-actions/repository_dispatch:
          # This has to be done as part of the `store_artifacts` job, since GitHub
          # needs this job's number in order to download the artifacts
          repo_name: "movermeyer/octokit_test"
          event_type: "wheel_build_complete"
    docker:
      - image: circleci/python:3.9
