name: Add artifacts to GitHub draft release

on:
  repository_dispatch:
    types: [wheel_build_complete]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download the artifacts from CircleCI
        run: |
          echo ${{ github.event.client_payload.build_num }} &&
          echo ${{ github.event.client_payload.build_url }} &&
          curl "${{ github.event.client_payload.build_url }}/artifacts" \
          --header 'Circle-Token: ${{ secrets.circle_token }}' \
          --header 'Content-Type: application/json'
