name: Add artifacts to GitHub draft release

on:
  release:
    # types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Debug dump
        run: |
          echo ${{ github.event.release }}
      - name: Trigger wheel build
        # if: github.event.release.draft == true
        run: |
          curl --location --request POST 'https://circleci.com/api/v2/project/gh/movermeyer/octokit_test/pipeline' \
          --header 'Circle-Token: ${{ secrets.circle_token }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "branch": ${{ github.event.release.tag_name }},
            "parameters": {
              "build_wheels": true
            }
          }'
