name: Add artifacts to GitHub draft release

on:
  repository_dispatch:
    types: [wheel_build_complete]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download the artifacts from CircleCI
        run: |
          echo ${{ github.event.client_payload }} | jq '.build_num' &&
          echo ${{ github.event.client_payload }} | jq '.build_url' &&
          BUILD_URL=`echo ${{ github.event.client_payload }} | jq '.build_url'` &&
          curl "${BUILD_URL}/artifact" \
          --header 'Circle-Token: ${{ secrets.circle_token }}' \
          --header 'Content-Type: application/json'
