name: Create draft GitHub release

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+" # glob

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Create draft GitHub release
        # Note: Creating a draft release does NOT trigger a `release` event
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Trigger wheel build
        run: |
          curl --location --request POST 'https://circleci.com/api/v2/project/gh/movermeyer/octokit_test/pipeline' \
          --header 'Circle-Token: ${{ secrets.circle_token }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "branch": "${{ github.event.ref }}",
            "parameters": {
              "build_wheels": true
            }
          }'
